ALTER TABLE answer ENGINE=INNODB;
ALTER TABLE question ENGINE=INNODB;
ALTER TABLE question_results ENGINE=INNODB;
ALTER TABLE quiz ENGINE=INNODB;
ALTER TABLE quiz_results ENGINE=INNODB;
ALTER TABLE users ENGINE=INNODB;

ALTER TABLE question ADD create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE answer ADD create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE quiz ADD create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;


