ALTER TABLE answer ENGINE=INNODB;
ALTER TABLE question ENGINE=INNODB;
ALTER TABLE question_results ENGINE=INNODB;
ALTER TABLE quiz ENGINE=INNODB;
ALTER TABLE quiz_results ENGINE=INNODB;
ALTER TABLE users ENGINE=INNODB;

ALTER TABLE question ADD create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE answer ADD create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE quiz ADD create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE quiz_results CHANGE COLUMN complete_date complete_date TIMESTAMP NOT NULL DEFAULT '0000-00-00';
ALTER TABLE quiz_results CHANGE COLUMN correct_points correct_points INT DEFAULT 0;
ALTER TABLE quiz_results CHANGE COLUMN total_points total_points INT DEFAULT 0;

